Repository/Repository/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import rootview
urlpatterns = [

    # url(r"^notifications/", include("pinax.notifications.urls", name="pinax_notifications")),
    url(r'^collec/', include('collec.urls'), name='collec'),
    url(r'^login/$', rootview.mylogin),
    url(r'^forget_password/$', rootview.forget_password),
    url(r'^admin/',include(admin.site.urls)),
    url(r'^$', rootview.mylogin),
]

Repository/collec/urls.py
# -*- coding:utf-8 -*-

from django.conf.urls import url
from collec import views
app_name = 'collec'
urlpatterns = [
    url(r'^addOrder/', views.addOrder, name='addOrder'),
    url(r'^receive/', views.receive, name='receive'),
    url(r'^receiveOrder/(.+)/$', views.receiveOrder, name='receiveOrder'),
    url(r'^sendAssetAmount/$', views.sendAssetAmount, name='sendAssetAmount'),
    url(r'^cancleReceiveAmount/$', views.cancleReceiveAmount, name='cancleReceiveAmount'),
    url(r'^submit/', views.submit, name='submit'),
    url(r'^detail/$', views.detail, name="detail"),
    url(r'^mylogout/$',views.my_logout, name="mylogout"),
    url(r'^changepd/$',views.changepd, name="changepd"),
    url(r'^index/$', views.index, name="index"),
    url(r'^vendormanage/$', views.vendormanage, name="vendormanage"),
    url(r'^deleteUser/(?P<id>[0-9]{1,6})/$', views.deleteUser, name='deleteUser'),
    url(r'^addUser/$', views.addUser, name="addUser"),
    url(r'^deleteuser/(.+)/$', views.deleteuser, name="deleteuser"),
    url(r'^orderajax/$', views.orajax,name='ordajax'),
    url(r'^assetajax/$', views.asetajax,name='assetajax'),
    url(r'^ajaxreceiveorder/$', views.ajaxrecveorder,name='ajaxreceiveorder'),
    url(r'^ajaxreceived/', views.ajaxreceived, name='ajaxreceived'),
    url(r'^receivedassetajax/', views.receivedassetajax, name='receivedassetajax'),
    url(r'^ajaxsubmited/$', views.ajaxsubmited, name='ajaxsubmited'),
    url(r'^submitedassetajax/$', views.submitedassetajax, name='submitedassetajax'),
    url(r'^ajax_saveReceive/$', views.ajax_saveReceive, name='ajax_saveReceive'),
    url(r'^ajax_vendor_comment_save/$', views.ajax_vendorcomment_save, name='ajax_vendor_comment_save'),
    url(r'^searchorder/$', views.searchorder, name='searchorder'),
    url(r'^ajax_searchOrder/$', views.ajax_searchOrder, name='ajax_searchOrder'),
    url(r'^ajax_searchasset/$', views.ajax_searchasset, name='ajax_searchasset'),
    url(r'^ajax_vendor_send/$', views.ajax_vendor_send, name='ajax_vendor_send'),
    url(r'^createOrder/$', views.createOrder, name='createOrder'),
    url(r'^updateOrder/(.+)/$', views.updateOrder, name='updateOrder'),
    url(r'^upload_order/$', views.upload_order, name='upload_order'),
    url(r'^import_excelFile/$', views.import_excelFile, name='import_excelFile'),
    url(r'^download_excle/$', views.download_excle, name='download_excle'),
    url(r'^showInfo/$',views.showInfo,name='showInfo'),
    url(r'^change_personal_Info/$',views.change_personalInfo,name='change_personalInfo'),
    url(r'^export/$', views.export, name='export'),
    url(r'^sendpassword_eamil/$', views.sendpassword_eamil, name='sendpassword_eamil'),
    url(r'^orderStatus/$',views.orderStatus,name="orderStatus"),
    url(r'^ajax_getOption/$', views.ajax_getOption, name="ajax_getOption"),
    url(r'^add_user/$', views.add_user, name="add_user"),
    url(r'^form_adduser/$', views.form_adduser, name="form_adduser"),
    url(r'^import_user/$', views.import_user, name="import_user"),
    url(r'^import_user_excle/$', views.import_user_excle, name="import_user_excle"),
    url(r'^add_notice/$', views.add_notice, name="add_notice"),
    url(r'^form_addnotice/$', views.form_addnotice, name="form_addnotice"),
    url(r'^download_user_excle/$', views.download_user_excle, name="download_user_excle"),
    url(r'^admin_password_change/$', views.admin_password_change, name="admin_password_change"),
    url(r'^mailbox/$', views.mailbox, name='mailbox'),



]

Repository/collec/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.db import models
from  django.contrib.auth.models import User
from django.utils.html import *


class Asset(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,verbose_name='sender')
    orderID = models.ForeignKey('Order',on_delete=models.CASCADE,verbose_name='orderID')
    Category = models.CharField(max_length=512,null=True,help_text="Category")
    PartNo =  models.CharField(max_length=512,null=True,help_text="PartNo")
    SN = models.CharField(max_length=512, null=True, help_text="SN")
    ProductDescription = models.CharField(max_length=512, null=True, help_text="ProductDescription")
    Qty = models.IntegerField(null=True, help_text="Qty")
    receiveQty = models.IntegerField(null=True,help_text="receiveQty")
    submitButton = models.CharField(max_length=512, default='NO', help_text="submitButton")
    receiveButton = models.CharField(max_length=512, default='NO', help_text="receiveButton")

    def __str__(self):
        return self.PartNo

        # 将属性和属性值转换成dict 列表生成式
    def toDict(self):
         return dict([(attr, getattr(self, attr)) for attr in [f.name for f in self._meta.fields]])

class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='sent_user')
    receive_user = models.CharField(max_length=512, verbose_name='receive_user')
    orderId = models.CharField(max_length=512, help_text="orderId")
    Shipfrom = models.CharField(max_length=512, null=True, help_text="shipfrom")
    Shipto = models.CharField(max_length=512, null=True, help_text="shipto")
    PO = models.CharField(max_length=512, null=True, help_text="PO")
    Forwarder = models.CharField(max_length=512, null=True, help_text="Forwarder")
    Packages = models.IntegerField(null=True, help_text="Packages")
    NetWeight = models.CharField(max_length=512, help_text="NetWeight")
    GrossWeight = models.CharField(max_length=512, help_text="GrossWeight")
    Volume = models.CharField(max_length=512, help_text="Volume")
    Tracking = models.CharField(max_length=512, help_text="Tracking")
    ordersubmitButton = models.CharField(max_length=512, default='NO', help_text="ordersubmitButton")
    orderreceiveButton = models.CharField(max_length=512, default='NO', help_text="orderreceiveButton")
    vendorcomments = models.CharField(max_length=512,null=True,help_text="vendorcomments")
    receivecommets = models.CharField(max_length=512,null=True,help_text="receivecommets")
    sendOrder_time = models.DateTimeField(null=True,help_text="send_Order_time")
    receiveOrder_time = models.DateTimeField(null=True,help_text="receive_Order_time")
    send_vendor_comment = models.CharField(max_length=512,default='NO',help_text="send_vendor_comment")
    receive_vendor_comment = models.CharField(max_length=512,default='NO',help_text="receive_vendor_comment")
    create_Order_time = models.DateTimeField(null=True,help_text="create_Order_time")

    def __str__(self):
        return self.orderId

    def toDict(self):
        return dict([(attr, getattr(self, attr)) for attr in [f.name for f in self._meta.fields]])

class Company(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    Contact = models.EmailField(null=True)
    Phone = models.CharField(max_length=255)

class ExtendUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    Country = models.CharField(max_length=255, help_text="Country", null=True)
    City = models.CharField(max_length=255, help_text="City", null=True)
    Email = models.EmailField(max_length=255,help_text="Email",null=True)
    Phone = models.CharField(max_length=255,help_text="Phone",null=True)
    clear_password =models.CharField(max_length=255,null=True)
    User_Status = models.CharField(max_length=255,null=True,default='vendor')



class Notice(models.Model):
    content = models.CharField(max_length=255, help_text="content", null=True)

Repository/collec/forms.py
from django import forms


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField()


class ChangePasswordForm(forms.Form):
    old_password = forms.CharField()
    new_password1 = forms.CharField()
    new_password2 = forms.CharField()

Repository/templates/Smart_Delivery_AddUser.html
<!DOCTYPE html>

<html lang="en" >
<head>
<title>Add extend user | Smart Delivery Management</title>
<link rel="stylesheet" type="text/css" href="/static/admin/css/base.css" />
<link rel="stylesheet" type="text/css" href="/static/admin/css/forms.css" />


<script type="text/javascript" src="/admin/jsi18n/"></script>
<script type="text/javascript" src="/static/admin/js/core.js"></script>
<script type="text/javascript" src="/static/admin/js/vendor/jquery/jquery.js"></script>
<script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>
<script type="text/javascript" src="/static/admin/js/admin/RelatedObjectLookups.js"></script>
<script type="text/javascript" src="/static/admin/js/actions.js"></script>
<script type="text/javascript" src="/static/admin/js/urlify.js"></script>
<script type="text/javascript" src="/static/admin/js/prepopulate.js"></script>
<script type="text/javascript" src="/static/admin/js/vendor/xregexp/xregexp.js"></script>

<meta name="robots" content="NONE,NOARCHIVE" />
</head>


<body class=" app-collec model-extenduser change-form"
  data-admin-utc-offset="28800">

<!-- Container -->
<div id="container">


    <!-- Header -->
    <div id="header">
        <div id="branding">

<h1 id="site-name">Smart Delivery Management</h1>

        </div>


        <div id="user-tools">

                WELCOME
                <strong>{{request.user.username}}</strong>.

                <a href="/collec/admin_password_change/">CHANGE PASSWORD</a> /

                <a href="/collec/mylogout/">LOG OUT</a>

        </div>



    </div>
    <!-- END Header -->

<div class="breadcrumbs">
<a href="javascrip:;">Login</a>
&rsaquo; <a href="/admin/collec/extenduser/">Extend users</a>
&rsaquo; Add extend user
</div>
    <!-- Content -->
    <div id="content" class="colM">
        <div id="content-main">



<form  action="/collec/form_adduser/" method="post" id="extenduser_form" >
    {% csrf_token %}
<div>

  <fieldset class="module aligned ">

    <div class="form-row" style="font-size: 18px">Add_User_Information:</div>

        <div class="form-row field-user" style="padding: 10px 100px">
              <div>
                        <label class="required" for="id_Country">User_Status:</label>
                        <select name="user_status" >
                            <option value="vendor">vendor</option>
                            <option value="receiver">receiver</option>
                        </select>


                </div>


        </div>

        <div class="form-row field-user" style="padding: 10px 100px">
              <div>


                        <label class="required" for="id_Country">Username:</label>

                    <input type="text" name="Username" id="id_Username" required="required" class="vTextField"      maxlength="255" />




                        <div class="help">Username</div>

                </div>


        </div>


        <div class="form-row field-password" style="padding: 10px 100px">
              <div>


                        <label class="required" for="id_Country">Password:</label>

                    <input type="text" name="Password" id="id_Password" required="required" class="vTextField"      maxlength="255" />




                        <div class="help">Password</div>

                </div>


        </div>


        <div class="form-row field-Country" style="padding: 10px 100px">


                <div>


                        <label class="required" for="id_Country">Country:</label>

                    <input type="text" name="Country" id="id_Country" required="required" class="vTextField"      maxlength="255" />




                        <div class="help">Country</div>

                </div>

        </div>


        <div class="form-row field-City" style="padding: 10px 100px">


                <div>


                        <label class="required" for="id_City">City:</label>

                            <input type="text" name="City" id="id_City" required="required" class="vTextField" maxlength="255" />



                        <div class="help">City</div>

                </div>

        </div>


        <div class="form-row field-Email" style="padding: 10px 100px">


                <div>


                        <label class="required" for="id_Email">Email:</label>

                            <input type="text" name="Email" id="id_Email" required="required" class="vTextField" maxlength="255" />



                        <div class="help">Email</div>

                </div>

        </div>


        <div class="form-row field-Phone" style="padding: 10px 100px">


                <div>


                        <label class="required" for="id_Phone">Phone:</label>

                            <input type="text" name="Phone" id="id_Phone" required="required" class="vTextField" maxlength="255" />



                        <div class="help">Phone</div>

                </div>

        </div>


</fieldset>



<div class="submit-row">
<input type="submit" value="ADD" class="default" name="_save" />
</div>



    <!--<script type="text/javascript"-->
            <!--id="django-admin-form-add-constants"-->
            <!--src="/static/admin/js/change_form.js"-->

                <!--data-model-name="extenduser"-->
            <!--&gt;-->
    <!--</script>-->




<!--<script type="text/javascript"-->
        <!--id="django-admin-prepopulated-fields-constants"-->
        <!--src="/static/admin/js/prepopulate_init.js"-->
        <!--data-prepopulated-fields="[]">-->
<!--</script>-->


</div>
</form>
 </div>


        <br class="clear" />
    </div>
    <!-- END Content -->

    <div id="footer"></div>
</div>
<!-- END Container -->

</body>
</html>

Repository/templates/admin_user_changepd.html
{% load static %}
<html lang="en" >
<head>
<title>Change Password | Smart Delivery Management</title>
<link rel="stylesheet" type="text/css" href="/static/admin/css/base.css" />
<link rel="stylesheet" type="text/css" href="/static/admin/css/forms.css" />
<script type="text/javascript" src="/admin/jsi18n/"></script>
<script type="text/javascript" src="/static/admin/js/core.js"></script>
<script type="text/javascript" src="/static/admin/js/vendor/jquery/jquery.js"></script>
<script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>
<script type="text/javascript" src="/static/admin/js/admin/RelatedObjectLookups.js"></script>
<script type="text/javascript" src="/static/admin/js/actions.js"></script>
<script type="text/javascript" src="/static/admin/js/urlify.js"></script>
<script type="text/javascript" src="/static/admin/js/prepopulate.js"></script>
<script type="text/javascript" src="/static/admin/js/vendor/xregexp/xregexp.js"></script>
<script type="text/javascript" src="{% static 'plugins/jQuery/jquery-2.2.3.min.js'%}"></script>
<meta name="robots" content="NONE,NOARCHIVE" />
</head>
<body class=" app-collec model-extenduser change-form"
  data-admin-utc-offset="28800">

<!-- Container -->
<div id="container">
    <!-- Header -->
    <div id="header">
        <div id="branding">

<h1 id="site-name">Smart Delivery Management</h1>
        </div>
        <div id="user-tools">

                WELCOME
                <strong>{{request.user.username}}</strong>.

                CHANGE PASSWORD /

                <a href="/collec/mylogout/">LOG OUT</a>

        </div>



    </div>
    <!-- END Header -->

<div class="breadcrumbs">
<a href="javascrip:;">Login</a>
&rsaquo; <a href="/admin/collec/extenduser/">Extend users</a>
&rsaquo; Change Password
</div>

    <!-- Content -->
    <div id="content" class="colM">
        <div id="content-main">
     <form method="post" action="/collec/changepd/">
          {% csrf_token %}
<div>



<p>Please enter your old password, for security's sake, and then enter your new password twice so we can verify you typed it in correctly.</p>

<fieldset class="module aligned wide">

<div class="form-row">

    <label class="required" for="id_old_password">Old password:</label> <input type="password" name="old_password" autofocus required id="id_old_password" />
</div>

<div class="form-row">

    <label class="required" for="id_new_password1">New password:</label> <input type="password" name="new_password1" required id="id_new_password1" />

    <div class="help"><ul><li>Your password can&#39;t be too similar to your other personal information.</li><li>Your password must contain at least 8 characters.</li><li>Your password can&#39;t be a commonly used password.</li><li>Your password can&#39;t be entirely numeric.</li></ul></div>

</div>

<div class="form-row">

    <label class="required" for="id_new_password2">New password confirmation:</label> <input type="password" name="new_password2" required id="id_new_password2" />

</div>

</fieldset>

<div class="submit-row">
    <input type="submit" value="Change my password" class="default" />
</div>

</div>
</form>




 </div>



    </div>
    <!-- END Content -->

    <div id="footer"></div>
</div>
<!-- END Container -->
</body>
</html>

Repository/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
  <meta http-equiv="Pragma" content="no-cache">
  <meta http-equiv="Cache-Control" content="no-cache">
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>{% block title %}main{% endblock %}</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.6 -->
  <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'plugins/font-awesome-4.6.3/css/font-awesome.min.css' %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="{% static 'plugins/ionicons-2.0.1/css/ionicons.min.css' %}">


  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="{% static 'plugins/html5shiv.min.js' %}"></script>
  <script src="{% static 'plugins/respond.min.js' %}"></script>
  <![endif]-->

  {% block css %}{% endblock %}

</head>
<body class="hold-transition skin-blue sidebar-mini">

<div class="wrapper">

  <header class="main-header">
    <!-- Logo -->

    <a href="#" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini">Smart Delivery </span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg"><b>Smart Delivery</b></span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a>


      <div class="navbar-custom-menu">

        <ul class="nav navbar-nav" >

          <li class="user user-menu" style="margin-right:40px;bottom:-2px;" >
              <img  src="{% static 'dist/img/nokia_logo.png' %}"  alt="Nokia Image">
          </li>
           <!--Control Sidebar Toggle Button-->

        </ul>

        <ul class="nav navbar-nav">

          <li class="user user-menu">
              <a style="width:100%;height:100%;"  href="{% url 'collec:export' %}"><span><i class="fa fa-sign-out fa-fw"></i></span><span>Export(数据导出)</span></a>
          </li>
           <!--Control Sidebar Toggle Button-->

        </ul>

        <ul class="nav navbar-nav">

          <li class="user user-menu">
              <a style="width:100%;height:100%;"  href="{% url 'collec:changepd' %}"><span><i class="fa fa-sign-out fa-fw"></i></span><span>Change Password(更改密码)</span></a>
          </li>
           <!--Control Sidebar Toggle Button-->

        </ul>

        <ul class="nav navbar-nav">
          <li class="user user-menu">
                <a style="width:100%;height:100%;"  href="{% url 'collec:mylogout' %}"><span><i class="fa fa-sign-out fa-fw"></i></span><span>Sign out(退出)</span></a>
          </li>
           <!--Control Sidebar Toggle Button-->
          <li  class="nav-item" >
             <a href=""  data-widget="control-sidebar" data-slide="true" data-toggle="control-sidebar" >
                <i class="fa fa-th-large"></i>
             </a>
          </li>
        </ul>
      </div>
    </nav>
  </header>
  <!-- Left side column. contains the logo and sidebar -->

  <aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
      <!-- Sidebar user panel -->
      <div  class="user-panel">
        <div class="pull-left image"  >
          {% if request.user.is_superuser  %}
          <img  src="{% static 'dist/img/user2-160x160.jpg' %}" class="img-circle" alt="User Image">
          {% else %}
          <img  src="{% static 'dist/img/avatar3.png' %}"  class="img-circle" alt="User Image">
          {% endif %}
        </div>
        <div class="pull-left info">
          <p>{{request.user.username}}</p>
          <a href="javascript:void(0);"><i class="fa fa-circle text-success"></i> Online</a>
        </div>
      </div>
      <!-- search form -->

      <!-- /.search form -->
      <!-- sidebar menu: : style can be found in sidebar.less -->
      <ul class="sidebar-menu">
        <li class="header">Navigation Bar</li>
          {% if request.user.is_superuser  %}
        <li class="active treeview"> 
          <a href="/collec/index/">
            <i class="fa fa-table"></i> <span>Search</span><br>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span>(搜索货运单)</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
        </li>
        <li class="active treeview">
          <a href="/collec/receive/">
            <i class="fa fa-table"></i><span>Created Shipment</span><br>
           &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span>(待处理货运单)</span>
              <!--<span class="label label-warning">{{recevingcount}}</span>-->
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
        </li>
        <li class="active treeview">
          <a href="/collec/detail/">
            <i class="fa fa-table"></i><span>Approved Shipment</span><br>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span>(完成的货运单)</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
        </li>
        <!--<li class="active treeview">-->
          <!--<a href="/collec/vendormanage/">-->
            <!--<i class="fa fa-table"></i> <span>Vendor Management</span><br>-->
           <!--&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span>(供应商管理)</span>-->
            <!--<span class="pull-right-container">-->
              <!--<i class="fa fa-angle-left pull-right"></i>-->
            <!--</span>-->
          <!--</a>-->
        <!--</li>-->
      
         {% else %}
        <li class="active treeview">
          <a href="/collec/index/">
            <i class="fa fa-table"></i> <span>Search</span><br>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span>(搜索货运单)</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
        </li>
        <li class="active treeview">
          <a href="/collec/createOrder/">
            <i class="fa fa-table"></i> <span>New Shipment</span><br>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span>(创建货运单)</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
        </li>
        <li class="active treeview">
          <a href="/collec/upload_order/">
            <i class="fa fa-table"></i> <span>Import Shipment</span><br>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span>(导入货运单)</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
        </li>
        <li class="active treeview">
          <a href="/collec/submit/">
            <i class="fa fa-table"></i> <span>Shipment Created List</span><br>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span>(货运单列表)</span>
               <!--<span class="label label-warning">{{submitedcount}}</span>-->
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
        </li>
        <li class="active treeview">
          <a href="/collec/showInfo/">
            <i class="fa fa-table"></i> <span>Vendor Information</span><br>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span>(供应商信息)</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
        </li>
         {% endif %}
      </ul>
    </section>
  </aside>
  <aside  class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->

   </aside>


  <!-- Content Wrapper. Contains page content -->

  <div class="content-wrapper">


      {% block content %}{% endblock %}

  </div>

  <!-- /.content-wrapper -->
  <footer   style="text-align:center;" class="main-footer" >
    <div class="pull-right hidden-xs">

    </div>
    <div>
       <strong>Contact Us:&nbsp;&nbsp;&nbsp;<a>labsupport.hangzhou@nokia.com</a></strong>
    </div>
    <br>
    <div>
    <strong>Copyright &copy; 2018-Cloud Development Services Lab Operations HangZhou & Telco Cloud China All rights
    reserved</strong>
    </div>
  </footer>

</div>
<!-- ./wrapper -->

<!-- jQuery 2.2.3 -->
<script src="{% static 'plugins/jQuery/jquery-2.2.3.min.js' %}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{% static 'plugins/jQueryUI/jquery-ui.min.js' %}"></script>


<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button);
</script>
<!-- Bootstrap 3.3.6 -->
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'build/js/ControlSidebar.js' %}"></script>
<script src="{% static 'plugins/bootstrap-slider/bootstrap-slider.js' %}"></script>
<script src="{% static 'build/js/Treeview.js' %}"></script>

{% block script %}{% endblock %}

</body>
</html>

Repository/templates/base_site.html
{% extends "admin_base.html" %}

{% block title %}{{ title }} | {{ site_title|default:_('Django Management') }}{% endblock %}

{% block branding %}
<h1 id="site-name"><a href="javascript:;">{{ site_header|default:_('Smart Delivery Management') }}</a></h1>
{% endblock %}

{% block nav-global %}{% endblock %}