Repository/Repository/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import rootview
urlpatterns = [

    # url(r"^notifications/", include("pinax.notifications.urls", name="pinax_notifications")),
    url(r'^collec/', include('collec.urls'), name='collec'),
    url(r'^login/$', rootview.mylogin),
    url(r'^forget_password/$', rootview.forget_password),
    url(r'^admin/',include(admin.site.urls)),
    url(r'^$', rootview.mylogin),
]

Repository/collec/urls.py
# -*- coding:utf-8 -*-

from django.conf.urls import url
from collec import views
app_name = 'collec'
urlpatterns = [
    url(r'^addOrder/', views.addOrder, name='addOrder'),
    url(r'^receive/', views.receive, name='receive'),
    url(r'^receiveOrder/(.+)/$', views.receiveOrder, name='receiveOrder'),
    url(r'^sendAssetAmount/$', views.sendAssetAmount, name='sendAssetAmount'),
    url(r'^cancleReceiveAmount/$', views.cancleReceiveAmount, name='cancleReceiveAmount'),
    url(r'^submit/', views.submit, name='submit'),
    url(r'^detail/$', views.detail, name="detail"),
    url(r'^mylogout/$',views.my_logout, name="mylogout"),
    url(r'^changepd/$',views.changepd, name="changepd"),
    url(r'^index/$', views.index, name="index"),
    url(r'^vendormanage/$', views.vendormanage, name="vendormanage"),
    url(r'^deleteUser/(?P<id>[0-9]{1,6})/$', views.deleteUser, name='deleteUser'),
    url(r'^addUser/$', views.addUser, name="addUser"),
    url(r'^deleteuser/(.+)/$', views.deleteuser, name="deleteuser"),
    url(r'^orderajax/$', views.orajax,name='ordajax'),
    url(r'^assetajax/$', views.asetajax,name='assetajax'),
    url(r'^ajaxreceiveorder/$', views.ajaxrecveorder,name='ajaxreceiveorder'),
    url(r'^ajaxreceived/', views.ajaxreceived, name='ajaxreceived'),
    url(r'^receivedassetajax/', views.receivedassetajax, name='receivedassetajax'),
    url(r'^ajaxsubmited/$', views.ajaxsubmited, name='ajaxsubmited'),
    url(r'^submitedassetajax/$', views.submitedassetajax, name='submitedassetajax'),
    url(r'^ajax_saveReceive/$', views.ajax_saveReceive, name='ajax_saveReceive'),
    url(r'^ajax_vendor_comment_save/$', views.ajax_vendorcomment_save, name='ajax_vendor_comment_save'),
    url(r'^searchorder/$', views.searchorder, name='searchorder'),
    url(r'^ajax_searchOrder/$', views.ajax_searchOrder, name='ajax_searchOrder'),
    url(r'^ajax_searchasset/$', views.ajax_searchasset, name='ajax_searchasset'),
    url(r'^ajax_vendor_send/$', views.ajax_vendor_send, name='ajax_vendor_send'),
    url(r'^createOrder/$', views.createOrder, name='createOrder'),
    url(r'^updateOrder/(.+)/$', views.updateOrder, name='updateOrder'),
    url(r'^upload_order/$', views.upload_order, name='upload_order'),
    url(r'^import_excelFile/$', views.import_excelFile, name='import_excelFile'),
    url(r'^download_excle/$', views.download_excle, name='download_excle'),
    url(r'^showInfo/$',views.showInfo,name='showInfo'),
    url(r'^change_personal_Info/$',views.change_personalInfo,name='change_personalInfo'),
    url(r'^export/$', views.export, name='export'),
    url(r'^sendpassword_eamil/$', views.sendpassword_eamil, name='sendpassword_eamil'),
    url(r'^orderStatus/$',views.orderStatus,name="orderStatus"),
    url(r'^ajax_getOption/$', views.ajax_getOption, name="ajax_getOption"),
    url(r'^add_user/$', views.add_user, name="add_user"),
    url(r'^form_adduser/$', views.form_adduser, name="form_adduser"),
    url(r'^import_user/$', views.import_user, name="import_user"),
    url(r'^import_user_excle/$', views.import_user_excle, name="import_user_excle"),
    url(r'^add_notice/$', views.add_notice, name="add_notice"),
    url(r'^form_addnotice/$', views.form_addnotice, name="form_addnotice"),
    url(r'^download_user_excle/$', views.download_user_excle, name="download_user_excle"),
    url(r'^admin_password_change/$', views.admin_password_change, name="admin_password_change"),
    url(r'^mailbox/$', views.mailbox, name='mailbox'),



]

Repository/collec/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.db import models
from  django.contrib.auth.models import User
from django.utils.html import *


class Asset(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,verbose_name='sender')
    orderID = models.ForeignKey('Order',on_delete=models.CASCADE,verbose_name='orderID')
    Category = models.CharField(max_length=512,null=True,help_text="Category")
    PartNo =  models.CharField(max_length=512,null=True,help_text="PartNo")
    SN = models.CharField(max_length=512, null=True, help_text="SN")
    ProductDescription = models.CharField(max_length=512, null=True, help_text="ProductDescription")
    Qty = models.IntegerField(null=True, help_text="Qty")
    receiveQty = models.IntegerField(null=True,help_text="receiveQty")
    submitButton = models.CharField(max_length=512, default='NO', help_text="submitButton")
    receiveButton = models.CharField(max_length=512, default='NO', help_text="receiveButton")

    def __str__(self):
        return self.PartNo

        # 将属性和属性值转换成dict 列表生成式
    def toDict(self):
         return dict([(attr, getattr(self, attr)) for attr in [f.name for f in self._meta.fields]])

class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='sent_user')
    receive_user = models.CharField(max_length=512, verbose_name='receive_user')
    orderId = models.CharField(max_length=512, help_text="orderId")
    Shipfrom = models.CharField(max_length=512, null=True, help_text="shipfrom")
    Shipto = models.CharField(max_length=512, null=True, help_text="shipto")
    PO = models.CharField(max_length=512, null=True, help_text="PO")
    Forwarder = models.CharField(max_length=512, null=True, help_text="Forwarder")
    Packages = models.IntegerField(null=True, help_text="Packages")
    NetWeight = models.CharField(max_length=512, help_text="NetWeight")
    GrossWeight = models.CharField(max_length=512, help_text="GrossWeight")
    Volume = models.CharField(max_length=512, help_text="Volume")
    Tracking = models.CharField(max_length=512, help_text="Tracking")
    ordersubmitButton = models.CharField(max_length=512, default='NO', help_text="ordersubmitButton")
    orderreceiveButton = models.CharField(max_length=512, default='NO', help_text="orderreceiveButton")
    vendorcomments = models.CharField(max_length=512,null=True,help_text="vendorcomments")
    receivecommets = models.CharField(max_length=512,null=True,help_text="receivecommets")
    sendOrder_time = models.DateTimeField(null=True,help_text="send_Order_time")
    receiveOrder_time = models.DateTimeField(null=True,help_text="receive_Order_time")
    send_vendor_comment = models.CharField(max_length=512,default='NO',help_text="send_vendor_comment")
    receive_vendor_comment = models.CharField(max_length=512,default='NO',help_text="receive_vendor_comment")
    create_Order_time = models.DateTimeField(null=True,help_text="create_Order_time")

    def __str__(self):
        return self.orderId

    def toDict(self):
        return dict([(attr, getattr(self, attr)) for attr in [f.name for f in self._meta.fields]])

class Company(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    Contact = models.EmailField(null=True)
    Phone = models.CharField(max_length=255)

class ExtendUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    Country = models.CharField(max_length=255, help_text="Country", null=True)
    City = models.CharField(max_length=255, help_text="City", null=True)
    Email = models.EmailField(max_length=255,help_text="Email",null=True)
    Phone = models.CharField(max_length=255,help_text="Phone",null=True)
    clear_password =models.CharField(max_length=255,null=True)
    User_Status = models.CharField(max_length=255,null=True,default='vendor')



class Notice(models.Model):
    content = models.CharField(max_length=255, help_text="content", null=True)

Repository/collec/forms.py
from django import forms


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField()


class ChangePasswordForm(forms.Form):
    old_password = forms.CharField()
    new_password1 = forms.CharField()
    new_password2 = forms.CharField()

Repository/collec/templates/collec/detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Smart Delivery To Nokia{% endblock %}

{% block css %}

  <!-- DataTables -->
  <!--<link rel="stylesheet" href="{% static 'plugins/datatables/dataTables.bootstrap.css' %}">-->
  <link rel="stylesheet" href="{% static 'plugins/datatables/jquery.dataTables.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/AdminLTE.min.css' %}">
  <!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
  <link rel="stylesheet" href="{% static 'dist/css/skins/_all-skins.min.css' %}">
<style>
         td.details-control {
            text-align:center;
            color:forestgreen;
            cursor: pointer;
        }
        tr.shown td.details-control {
            text-align:center;
            color:red;
        }
                table{
         table-layout:fixed;
        }
        table tr td{
        word-wrap:break-word;
        white-space: nowrap;
        text-overflow: ellipsis;
        overflow: hidden;
        }
        table tr td:hover{
           overflow: visible;
           white-space: normal;
        }
        table.dataTable thead .sorting,
        table.dataTable thead .sorting_asc,
        table.dataTable thead .sorting_desc{
                background-image:none;
          }
</style>

{% endblock %}

{% block content %}

    <!--&lt;!&ndash; Content Header (Page header) &ndash;&gt;-->
    <section class="content-header">
      <h1>
      Approved Shipment
        <small>已完成货运单</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i>Main</a></li>
        <li class="active">Approved Shipment</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
       <div class="box">
        <!-- /.box-header -->
        <div class="box-body">

         <table style="width:100%;text-align:center;" class="display" id="example" cellspacing="0">
                  <thead>
                    <tr>
                        <th></th>
                        <th>index</th>
                        <th>ShipmentID<br>(运单ID)</th>
                        <th>Ship from<br>(发送方)</th>
                        <th>Ship to<br>(接收方)</th>
                        <th>Purchase Order<br>(合同号)</th>
                        <th>Forwarder<br>(承运商)</th>
                        <th>Gross Weight<br>(重量)</th>
                        <th>Volume<br>(体积)</th>
                        <th>Tracking NO.<br>(货运单号)</th>
                        <th>Packages Qty<br>(包裹数量)</th>
                        <th>Sent Time<br>(发送时间)</th>
                        <th>Receive Time<br>（接收时间）</th>

                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th></th>
                        <th>index</th>
                        <th>Shipment ID</th>
                        <th>Ship from</th>
                        <th>Ship to</th>
                        <th>Purchase Order</th>
                        <th>Forwarder</th>
                        <th>Gross Weight</th>
                        <th>Volume</th>
                        <th>Tracking NO.</th>
                        <th>Packages Qty</th>
                        <th>Sent Time</th>
                        <th>Received Time</th>

                    </tr>
                </tfoot>
            </table>


        </div>
        <!-- /.box-body -->
      </div>

      <!-- /.box -->
    </div>
    <!-- /.col -->
        </div>
    <!-- /.row -->
    </section>

{% endblock %}

{% block script %}
    <!-- DataTables -->
    <script src="{% static 'plugins/datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'plugins/datatables/dataTables.bootstrap.min.js' %}"></script>
    <!-- SlimScroll -->
    <script src="{% static 'plugins/slimScroll/jquery.slimscroll.min.js' %}"></script>
    <!-- FastClick -->
    <script src="{% static 'plugins/fastclick/fastclick.js' %}"></script>
    <!-- AdminLTE App -->
    <script src="{% static 'dist/js/app.min.js' %}"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="{% static 'dist/js/demo.js' %}"></script>
    <!-- page script -->
    <script>
         $(document).ready(function () {

         var table = $('#example').DataTable({
             "ajax": '/collec/ajaxreceived/',
             select:"single",
             "columns": [
                 {
                     "className": 'details-control',
                     "orderable": false,
                     "data": null,
                     "defaultContent": '',
                     "render": function () {
                         return '<i class="fa fa-plus-square" aria-hidden="true"></i>';
                     },
                     width:"20px"
                 },
                  {
                     "targets": 1,
                     "orderable": true,
                     "data": null,
                     "defaultContent": '',
                    "render":function(data,type,row,meta){
                        var startIndex = meta.settings._iDisplayStart;
                         return startIndex+meta.row+1;
                     },
                     width:"20px"
                 },
                 { "data": "orderId" },
                 { "data": "Shipfrom" },
                 { "data": "Shipto" },
                 { "data": "PO" },
                 { "data": "Forwarder" },
                 { "data": "GrossWeight" },

                 { "data": "Volume" },
                 { "data": "Tracking" },
                 { "data": "Packages" },
                 { "data": "sendOrder_time","type":"date"

                  },
                 { "data": "receiveOrder_time","type":"date"
                }
             ],
             "order": [[1, 'asc']]
         });

         // Add event listener for opening and closing details
         $('#example tbody').on('click', 'td.details-control', function () {
             var tr = $(this).closest('tr');
             var tdi = tr.find("i.fa");
             var row = table.row(tr);

             if (row.child.isShown()) {
                 // This row is already open - close it
                 row.child.hide();
                 tr.removeClass('shown');
                 tdi.first().removeClass('fa-minus-square');
                 tdi.first().addClass('fa-plus-square');
             }
             else {

                 row.child(format(row.data())).show();
                 tr.addClass('shown');
                 tdi.first().removeClass('fa-plus-square');
                 tdi.first().addClass('fa-minus-square');
             }
         });

         table.on("user-select", function (e, dt, type, cell, originalEvent) {
             if ($(cell.node()).hasClass("details-control")) {
                 e.preventDefault();
             }
         });
     });

function format ( rowData ) {
    var dit = $('<div/>')
        .addClass( 'loading' )
        .text( 'Loading...' );

    $.ajax( {
        url: '/collec/receivedassetajax/',
        data: {"orderId":rowData.orderId},
        success: function ( dats ) {
            dit.html('<div  style="padding-left:100px;"'+'id='+'"'+'ddv'+rowData.orderId+'"'+'><table style="width:100%;text-align:center;" class="display"'+'id='+'"'+rowData.orderId+'"'+'>'+
        '<thead>'+
            '<tr>'+
                 '<th>Index</th>' +
                  '<th>Category</th>' +
                 '<th>Part Number</th>' +
                 '<th>Product Description:</th>' +
                 '<th>Serial NO./Delivery Methods</th>' +
                 '<th>Sent Quantity</th>' +
                 '<th>Receive Quantity</th>' +
            '</tr>'+
        '</thead>'+
        '<tbody >'+
         '</tbody>'+
    '</table></div>').removeClass( 'loading' );

     jt  =JSON.parse(dats)
     dat = jt.data;
      for(var i=0;i<dat.length;i++){
          count =i;
          count =count+1;
        $('#'+rowData.orderId+' tbody').append('<tr>' +
                 '<td>' + count+ '</td>' +
                  '<td>' + dat[i].Category + '</td>' +
                 '<td>' + dat[i].PartNo + '</td>' +
                 '<td>' + dat[i].ProductDescription+ '</td>' +
                 '<td>' +dat[i].SN + '</td>' +
                 '<td>' + dat[i].Qty + '</td>' +
                 '<td>'+dat[i].receiveQty+'</td>' +
             '</tr>');
        }

        $('#'+'ddv'+rowData.orderId).after('<div style="padding-left:100px;">'+
          '<div style="float:left;padding-left:0px;">'+
               '<h5 id="vendorcomments">Vendor comments:</h5>'+
               '<textarea name="vendorcomments" readonly="readonly"  style="outline:none;background:#ecf0f5;border:0px;height: 80px;width: 500px;resize: none;" >'+rowData.vendorcomments+'</textarea>'+
          '</div>'+
          '<div style="float:right;padding-right:0px;">'+
               '<h5 id="vendorcomments">receive comments:</h5>'+
               '<textarea  readonly="readonly"   style="outline:none;background:#ecf0f5;border:0px;height: 80px;width: 500px;resize: none;" >'+rowData.receivecommets+'</textarea>'+
           '</div></div>');
      }
    });
    return dit;
}
    </script>
{% endblock %}

Repository/collec/templates/collec/personInfo.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}Smart Delivery To Nokia{% endblock %}

{% block css %}

<!-- DataTables -->
  <link rel="stylesheet" href="{% static 'plugins/datatables/dataTables.bootstrap.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/AdminLTE.min.css' %}">
  <!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
  <link rel="stylesheet" href="{% static 'dist/css/skins/_all-skins.min.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'admin/css/base.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'admin/css/forms.css' %}" />

{% endblock %}

{% block content %}

    <!--&lt;!&ndash; Content Header (Page header) &ndash;&gt;-->
  <section class="content-header">
      <h1>
        Vendor Information
        <small>供应商信息</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Main</a></li>
        <li class="active">Vendor Information</li>
      </ol>
    </section>

    <!-- Main content -->
  <section class="content" >
    <div class="row">
    <div class="col-xs-12">

      <div class="box">
         <!--/.box-header -->
        <div class="box-body">
            <div id="content" class="colM">
        <div id="content-main">

<form method="post"  action="/collec/change_personal_Info/">
     {% csrf_token %}
<div>
<fieldset class="module aligned wide">

<div class="form-row">
    <label class="required" >User name:</label> <input id="username" value="{{request.user.username}}" type="text" name="username"  required disabled="disabled" />
</div>

<div class="form-row">

    <label class="required" >Country:</label> <input id="country" value="{{request.user.extenduser.Country}}" type="text" name="country"  required disabled="disabled"  />
</div>

<div class="form-row">
    <label class="required">City:</label> <input  id="city" type="text" value="{{request.user.extenduser.City}}" name="city" required disabled="disabled"/>
</div>

<div class="form-row">
    <label class="required">Phone:</label> <input  id="phone" type="text" value="{{request.user.extenduser.Phone}}" name="phone" required disabled="disabled"/>
</div>

<div class="form-row">
    <label class="required">Email:</label> <input id="email" value="{{request.user.email}}" type="text" name="email" required  disabled="disabled"/>
</div>

</fieldset>

<div class="submit-row">
    <input  type="button" value="Modify" class="default" id="modify" />
</div>

</div>
</form>
  </div>
        <br class="clear" />
    </div>
    <!-- END Content -->

        </div>
        <!-- /.box-body -->
      </div>
      <!-- /.box -->
    </div>
    <!-- /.col -->
    </div>
    <!-- /.row -->
    </section>

{% endblock %}

{% block script %}
    <!-- DataTables -->
    <script src="{% static 'plugins/datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'plugins/datatables/dataTables.bootstrap.min.js' %}"></script>
    <!-- SlimScroll -->
    <script src="{% static 'plugins/slimScroll/jquery.slimscroll.min.js' %}"></script>
    <!-- FastClick -->
    <script src="{% static 'plugins/fastclick/fastclick.js' %}"></script>
    <!-- AdminLTE App -->
    <script src="{% static 'dist/js/app.min.js' %}"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="{% static 'dist/js/demo.js' %}"></script>
    <script>
        $('#modify').click(function(){
            $('#country').removeAttr('disabled');
            $('#city').removeAttr('disabled');
            $('#email').removeAttr('disabled');
            $('#phone').removeAttr('disabled');
            $('#modify').replaceWith(' <input  type="submit" value="Save" class="default" id="save" />');
        });


    </script>

{% endblock %}

Repository/collec/templates/collec/vendorMange.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Smart Delivery To Nokia{% endblock %}

{% block css %}

<!-- DataTables -->
  <link rel="stylesheet" href="{% static 'plugins/datatables/jquery.dataTables.css' %}">
  <!--<link rel="stylesheet" href="{% static 'plugins/datatables/dataTables.bootstrap.css' %}">-->
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/AdminLTE.min.css' %}">
  <!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
  <link rel="stylesheet" href="{% static 'dist/css/skins/_all-skins.min.css' %}">

{% endblock %}

{% block content %}

    <!--&lt;!&ndash; Content Header (Page header) &ndash;&gt;-->
    <section class="content-header">
      <h1>
       Vendors Management
       <small>供应商管理</small>
      </h1>

      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Main</a></li>
        <li class="active">Vendors Manage</li>
      </ol>
    </section>


    <!-- Main content -->
    <section class="content">
        <div class="row">
             <div class="col-xs-12">

       <div class="box">
        <!-- /.box-header -->

        <div class="box-body">

          <table id="assets_table" class="table table-bordered table-striped">
            <thead>
            <tr>

              <th>Username</th>
              <th>Password</th>
              <th>Email</th>
              <th>Phone</th>
              <th>FirstName</th>
              <th>LastName</th>
              <th>Operation</th>
            </tr>
            </thead>
            <tbody>
                {% for us in users %}

                  {% if us.username  != request.user.username %}
                <tr>
                  <td>{{us.username}}</td>
                  <td>{{us.password}}</td>
                  <td>{{us.email}}</td>
                  <td>{{us.extenduser.Phone}}</td>
                  <td>{{us.first_name }}</td>
                  <td>{{us.last_name}}</td>
                  <td><a href="/collec/deleteUser/{{us.id}}/"  id="{{us.username}}"   class='down btn btn-default btn-xs'>delete</a></td>

                </tr>
                  {% endif %}
                {% endfor %}
            </tbody>
          </table>
             <br>
            <div align="center">
                <input type="button" value="addUser" onclick="addRowg()">
                <input type="button" value="CancleaddUser" onclick="delRow()">
                <button id="button">Sent Email</button>
            </div>
        </div>
        <!-- /.box-body -->
      </div>

      <!-- /.box -->
          </div>
    <!-- /.col -->
       </div>
    <!-- /.row -->
    </section>

{% endblock %}

{% block script %}
    <!-- DataTables -->
    <script src="{% static 'plugins/datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'plugins/datatables/dataTables.bootstrap.min.js' %}"></script>
    <!-- SlimScroll -->
    <script src="{% static 'plugins/slimScroll/jquery.slimscroll.min.js' %}"></script>
    <!-- FastClick -->
    <script src="{% static 'plugins/fastclick/fastclick.js' %}"></script>
    <!-- AdminLTE App -->
    <script src="{% static 'dist/js/app.min.js' %}"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="{% static 'dist/js/demo.js' %}"></script>
    <!-- page script -->
    <script>
      $(function () {
        var table = $("#assets_table").DataTable({
          "paging": false,
          "searching": true,
          "ordering": true,
          "info": true,
          "autoWidth": false,


        });

        $('#assets_table tbody').on( 'click', 'tr', function () {
          $(this).toggleClass('selected');
    } );
 
    $('#button').click( function () {

         var selectData = table.rows('.selected').data();
         var len = table.rows('.selected').data().length;
          if(len==0){
            alert('Please select Line!')
          }else{
              var arra = []
              var arrb = []
              for(var i=0;i<len;i++){
                  arra.push(selectData[i][2]);
                  arrb.push(selectData[i][0]);
              }
              $.ajax({
                url:'/collec/sendpassword_eamil/',
                data:{'usernames':JSON.stringify(arrb),'emails':JSON.stringify(arra)},
                success:function(ret){
                    alert('Send Email Successful!!!')
                 }
              });
          }

    } );

      });

       function addRowg(){
        var rows = document.getElementById('assets_table').rows.length ; //获取表格行数
        var newTr = assets_table.insertRow();//添加一行
        <!--var newTd7 = newTr.insertCell();
        <!--newTd7.innerHTML = '<th>'+rows+'</th>';-->
        var newTd0 = newTr.insertCell();//第一列
        newTd0.innerHTML = '<th><input type="text" id="addusername" name="username" style="width:100%;"  required></th>';
        var newTd1 = newTr.insertCell();
        newTd1.innerHTML = '<th><input type="text"  id="addpassword" name="password" style="width:100%;"  required></th>';
        var newTd2 = newTr.insertCell();
        newTd2.innerHTML =  '<th><input type="text"  id="addemail" name="email" style="width:100%;"  required></th>';
        var newTd6 = newTr.insertCell();
        newTd6.innerHTML =  '<th><input type="text"  id="addphone"  name="phone" style="width:100%;"  required></th>';
        var newTd3 = newTr.insertCell();
        newTd3.innerHTML =  '<th><input type="text"  id="addfirstname"  name="firstname" style="width:100%;"  required></th>';
        var newTd4 = newTr.insertCell();
        newTd4.innerHTML =  '<th><input type="text"  id="addlastname" name="lastname" style="width:100%;"  required></th>';
        var newTd5 = newTr.insertCell();
        newTd5.innerHTML =  "<th><a href='javascript:void(0);' onclick='addUser()'  class='down btn btn-default btn-xs' style='width:55%;'>save</a></th>";
    }

 function delRow(){
   var tbobj=document.getElementById('assets_table');
   var rows = document.getElementById('assets_table').rows.length ;
       if(tbobj.rows.length>3){
           tbobj.deleteRow(tbobj.rows.length-1);
       }else{
        if(tbobj.rows.length>3){
          tbobj.deleteRow(tbobj.rows.length-1);
        }
   }
}

         function addUser(){
          var uname = $('#addusername').val()
          var upassword = $('#addpassword').val()
          var uemail = $('#addemail').val()
          var ufirstname = $('#addfirstname').val()
          var ulastname = $('#addlastname').val()
          var uphone = $('#addphone').val()
            $.ajax({
               url:"{% url 'collec:addUser' %}",
               type:"GET",
               data:{"uname":uname,"upassword":upassword,"uemail":uemail,"ufirstname":ufirstname,"ulastname":ulastname,'uphone':uphone},
               <!--headers:{"X-CSRFToken":$("[name='csrfmiddlewaretoken']").val()},-->
               success:function(ret){
                    ret = JSON.parse(ret);
                    alert(ret["infor"])
                    window.location.href="/collec/vendormanage/";

                 }
             })
       }


    </script>
{% endblock %}